server:
  port: 9102

spring:
  application:
    name: dynamic-tp-adapter-dubbo-demo
  profiles:
    active: dev

  dynamic:
    tp:
      enabled: true
      enabledBanner: true           # 是否开启banner打印，默认true
      enabledCollect: true          # 是否开启监控指标采集，默认false
      collectorTypes: logging     # 监控数据采集器类型（logging | micrometer | internal_logging），默认micrometer
      monitorInterval: 5
      dubboTp:                                    # dubbo 线程池配置
        - threadPoolName: dubboTp#20880            # 名称规则：dubboTp + "#" + 协议端口
          threadPoolAliasName: 测试线程池
          corePoolSize: 100
          maximumPoolSize: 200
          keepAliveTime: 60
          notifyItems:                            # 报警项，不配置自动会按默认值配置（变更通知、容量报警、活性报警）
            - type: capacity                       # 报警项类型，查看源码 NotifyTypeEnum枚举类
              enabled: true
              threshold: 80                        # 报警阈值
              platforms: [ ding,wechat ]             # 可选配置，不配置默认拿上层platforms配置的所以平台
              interval: 120                        # 报警间隔（单位：s）