---
namespace: "default"
fileGroup: "dynamic-tp-polaris-cloud-demo"
fileName: "config/dynamic-tp.yml"
content: "# 动态线程池配置文件，建议单独开一个文件放到配置中心，字段详解看readme介绍\nspring:\n  dynamic:\n    tp:\n\
  \      enabled: true\n      enabledBanner: true           # 是否开启banner打印，默认true\n\
  \      enabledCollect: true          # 是否开启监控指标采集，默认false\n      collectorTypes:\
  \ micrometer,logging     # 监控数据采集器类型（logging | micrometer | internal_logging），默认\
  micrometer\n      logPath: /home/logs           # 监控日志数据路径，默认 ${user.home}/logs\n\
  \      monitorInterval: 5            # 监控时间间隔（报警判断、指标采集），默认5s\n      platforms:\
  \                    # 通知报警平台配置\n        - platform: wechat\n          urlKey: 3a7500-1287-4bd-a798-c5c3d8b69c\
  \  # 替换\n          receivers: test1,test2                   # 接受人企微名称\n        -\
  \ platform: ding\n          urlKey: f80dad441fcd655438f4a08dcd6a     # 替换\n    \
  \      secret: SECb5441fa6f375d5b9d21           # 替换，非sign模式可以没有此值\n          receivers:\
  \ 15810119805                   # 钉钉账号手机号\n        - platform: lark\n          urlKey:\
  \ 0d944ae7-b24a-40                 # 替换\n          receivers: test1,test2      \
  \             # 接受人飞书名称/openid\n      tomcatTp:                                \
  \    # tomcat web server线程池配置\n        corePoolSize: 100\n        maximumPoolSize:\
  \ 400\n        keepAliveTime: 60\n      jettyTp:                               \
  \      # jetty web server线程池配置\n        corePoolSize: 100\n        maximumPoolSize:\
  \ 400\n      undertowTp:                                  # undertow web server线\
  程池配置\n        corePoolSize: 100\n        maximumPoolSize: 400\n        keepAliveTime:\
  \ 60\n      hystrixTp:                                   # hystrix 线程池配置\n     \
  \   - threadPoolName: hystrix1\n          corePoolSize: 100\n          maximumPoolSize:\
  \ 400\n          keepAliveTime: 60\n      dubboTp:                             \
  \        # dubbo 线程池配置\n        - threadPoolName: dubboTp#20880\n          corePoolSize:\
  \ 100\n          maximumPoolSize: 400\n          keepAliveTime: 60\n      rocketMqTp:\
  \                                  # rocketmq 线程池配置\n        - threadPoolName: group1#topic1\n\
  \          corePoolSize: 200\n          maximumPoolSize: 400\n          keepAliveTime:\
  \ 60\n      executors:                                   # 动态线程池配置，都有默认值，采用默认值的可\
  以不配置该项，减少配置量\n        - threadPoolName: dtpExecutor1\n          executorType: common\
  \                     # 线程池类型common、eager：适用于io密集型\n          corePoolSize: 2\n\
  \          maximumPoolSize: 8\n          queueCapacity: 200\n          queueType:\
  \ VariableLinkedBlockingQueue   # 任务队列，查看源码QueueTypeEnum枚举类\n          rejectedHandlerType:\
  \ CallerRunsPolicy    # 拒绝策略，查看RejectedTypeEnum枚举类\n          keepAliveTime: 50\n\
  \          allowCoreThreadTimeOut: false                  # 是否允许核心线程池超时\n      \
  \    threadNamePrefix: test                         # 线程名前缀\n          waitForTasksToCompleteOnShutdown:\
  \ false        # 参考spring线程池设计，优雅关闭线程池\n          awaitTerminationSeconds: 5   \
  \                  # 单位（s）\n          preStartAllCoreThreads: false            \
  \      # 是否预热所有核心线程，默认false\n          runTimeout: 200                         \
  \       # 任务执行超时阈值，目前只做告警用，单位（ms）\n          queueTimeout: 100                 \
  \             # 任务在队列等待超时阈值，目前只做告警用，单位（ms）\n          taskWrapperNames: [\"ttl\"\
  ]                          # 任务包装器名称，集成TaskWrapper接口\n          notifyItems:   \
  \                  # 报警项，不配置自动会按默认值配置（变更通知、容量报警、活性报警、拒绝报警、任务超时报警）\n            -\
  \ type: capacity               # 报警项类型，查看源码 NotifyTypeEnum枚举类\n              enabled:\
  \ true\n              threshold: 80                # 报警阈值\n              platforms:\
  \ [ding,wechat]     # 可选配置，不配置默认拿上层platforms配置的所以平台\n              interval: 120\
  \                # 报警间隔（单位：s）\n            - type: change\n              enabled:\
  \ true\n            - type: liveness\n              enabled: true\n            \
  \  threshold: 80\n            - type: reject\n              enabled: true\n    \
  \          threshold: 1\n            - type: run_timeout\n              enabled:\
  \ true\n              threshold: 1\n            - type: queue_timeout\n        \
  \      enabled: true\n              threshold: 1\n"
version: 2
md5: "1e7471232027d72a007a4c5dc623bbf5"
